name: CI/CD Docker
 
on:
  push:
    branches: [ "main" ]
 
jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set image tag
        id: set_tag
        run: echo "IMAGE_TAG=0.0.0-sha.${GITHUB_SHA::7}" >> $GITHUB_OUTPUT 
 
      
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
 
      
      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/pratica-devops-python:${{ env.GITHUB_SHA::7 }}
          labels: |
            org.opencontainers.image.version=${{ steps.set_tag.outputs.IMAGE_TAG }}
 

      - name: Update latest tag 
        uses: silverlyra/latest-image-action@v0.1.0 
        with: 
          repository: ${{ secrets.DOCKERHUB_USERNAME }}/pratica-devops-python
          candidate-tag: ${{ env.GITHUB_SHA::7 }} 
          version-source: label:org.opencontainers.image.version
